---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aspecta-backend-auth-gitops
  namespace: aspecta-app
spec:
  encryptedData:
    INTERNAL_API_TOKEN: AgAuo9XTEUVdarColsa/rJI1PMslmjeg8Xk4+wI+w7grM52azrLF5qnqzzfL2pAN6XIzIdYT68iYDMEO9x/LGXKW3KyA04mq4kF5kAL66PQJWtfByAR77iTee8rdgPsOw1U51sfx+9uHdLnSCM5G8m7hnISWQ7H2FQD31w3aOnCLEZw39yRa+PT6A95akcXYcphS6te5IQ2u7oBiA+TMvT9oeR/3sa8R8Tsh80nU05zuCZzBhMI2+2jzk2jMkNMEGge/ZmhZoRvAZtxZOyMJY8Gm5EKfcsYj2UrVJhSL2C91SH813K3ui7eEu74Cx5wO1Flhz9396eG+U+BWFOitUE7f7gBF75VhDmbdls3Qxp5vc+SRMg0a90gA/V3i0VBlEcS3c/tSRrPGSBFKBv+QQhQla2MYVQ8JlKIYtvfaLLESSmzvGPWbxgrGQLjwQGZxPyLbwGPJg27a72k5iL3mxP/21CzTddtp9RML+oDM4wLoerYnUMMqVAu9AOVsSIEWplwPgCmwKFns/iLsG9wso7uvpE4K72URwBUHsdsah0sRIAAl3A5EH2ZQqjc9lXXByx8NtqAuNwHQrwbyp020Fv1burZI7wBTeyuAPNlOzrnFgzrC9KMMuVXwPD6wFJ7i2DiMpDxFNcvzkMQAhmo44DTiFnHbnE16UL2mQF7x/E0sBJ2MuSv7KoIn4N6NwnkHJAEDYo7Mx1CH9KIDR2+KkRR9ZQWnRV9VU7LA/TqBhj1w4qL+uiZj8H2D45dBbFMqDpT7eW57XSIp6hcQLc8Irhpm
  template:
    metadata:
      name: aspecta-backend-auth-gitops
      namespace: aspecta-app
