deployment:
  replicas: 1

service:
  spec:
    type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
  kubernetesCRD:
    enabled: false
  kubernetesGateway:
    enabled: false

ingressRoute:
  dashboard:
    enabled: false

api:
  dashboard: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
