apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspecta-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.14.0
    helm:
      releaseName: aspecta-metrics-server
      valuesObject:
        replicas: 1
        args:
          - --kubelet-insecure-tls
        nodeSelector:
          aspecta.io/pool: workers
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 192Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true