apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspecta-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 92.2.0
      helm:
        releaseName: aspecta-monitoring
        valueFiles:
          - $values/platform/monitoring/values-minikube.yaml

    - repoURL: https://github.com/jansoltys9/aspecta-k8s-assignment.git
      targetRevision: feat/platform-security-gitops
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true