apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aspecta-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: https://github.com/jansoltys9/aspecta-k8s-assignment.git
    targetRevision: feat/platform-security-gitops
    path: platform/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true